web:
  image: droptica/apache-php:7-xdebug-v1.5
  volumes:
    - ./app:/var/www/html
    - ./docker/custom_config/php.ini:/usr/local/etc/php/conf.d/php.ini:ro # enable xdebug
  links:
    - mysql:mysql
  environment:
    VIRTUAL_HOST: dcon-codeception-d8.dev,www.dcon-codeception-d8.dev

mysql:
  image: mysql:5.6
  volumes:
    - ./app_data/database:/var/lib/mysql
    - ./docker/custom_config/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
  environment:
    MYSQL_ROOT_PASSWORD: 123
    MYSQL_DATABASE: db
    MYSQL_USER: user
    MYSQL_PASSWORD: pass

phpmyadmin:
  image: nazarpc/phpmyadmin
  links:
    - mysql:mysql
  environment:
      VIRTUAL_HOST: phpmyadmin.dcon-codeception-d8.dev
